//go:build !ignore_autogenerated

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

func (in *RouteSpec) DeepCopyInto(out *RouteSpec) {
	*out = *in
}

func (in *RouteSpec) DeepCopy() *RouteSpec {
	if in == nil {
		return nil
	}
	out := new(RouteSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *OCPSupportWebSpec) DeepCopyInto(out *OCPSupportWebSpec) {
	*out = *in
	if in.Route != nil {
		in, out := &in.Route, &out.Route
		*out = new(RouteSpec)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.OAuthProxyResources != nil {
		in, out := &in.OAuthProxyResources, &out.OAuthProxyResources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.AllowedGroups != nil {
		in, out := &in.AllowedGroups, &out.AllowedGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *OCPSupportWebSpec) DeepCopy() *OCPSupportWebSpec {
	if in == nil {
		return nil
	}
	out := new(OCPSupportWebSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *OCPSupportWebStatus) DeepCopyInto(out *OCPSupportWebStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *OCPSupportWebStatus) DeepCopy() *OCPSupportWebStatus {
	if in == nil {
		return nil
	}
	out := new(OCPSupportWebStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *OCPSupportWeb) DeepCopyInto(out *OCPSupportWeb) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *OCPSupportWeb) DeepCopy() *OCPSupportWeb {
	if in == nil {
		return nil
	}
	out := new(OCPSupportWeb)
	in.DeepCopyInto(out)
	return out
}

func (in *OCPSupportWeb) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *OCPSupportWebList) DeepCopyInto(out *OCPSupportWebList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OCPSupportWeb, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *OCPSupportWebList) DeepCopy() *OCPSupportWebList {
	if in == nil {
		return nil
	}
	out := new(OCPSupportWebList)
	in.DeepCopyInto(out)
	return out
}

func (in *OCPSupportWebList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
